### ISSUE TITLE
Low integrity authentication is not working in Common Voice staging

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-deploy#217] opened 2018-08-24 15:16 UTC
STR:
1. Navigate to https://voice.allizom.org/admin
2. Enter email address (e.g: viorelaioia@gmail.com) and click "Send me an email to continue" button
3. Click the login link form email 

Expected:
Login works 

Actual:
Error message asking to login with Firefox accounts is displayed
![login to cv](https://user-images.githubusercontent.com/5293100/44592608-c0389980-a7c9-11e8-95c3-a12ab8ffa672.png)

**Comment by gene1wood** [comment] 2018-08-24 16:38
It looks like Common Voice moved to using a `action=signup` and as a result NLX is showing all connection types instead of the one's returned by the https://auth-dev.mozilla.auth0.com/public/api/pl6mWaOtBMeXzTY3fUw57ED80bVkrgU1/connections endpoint.

I'll open a bug on that and see if I can workaround it to find out if this problem is related to that or not.

**Comment by gene1wood** [comment] 2018-08-24 17:50
@viorelaioia What's a good way for me to reproduce this? When I attempt to login with, for example a restmail.net email address, I just get sent to https://voice.allizom.org/admin and see `unauthorized` on the page.

Is it possible your gmail account is permitted in Common Voice somehow?

**Comment by viorelaioia** [comment] 2018-08-27 12:05
@gene1wood , I reproduced this by trying to login passwordless with an email address that has Firefox Accounts as most secure method in auth0 dev. If the low integrity authentication is enabled, then I should be able to login passwordless. 
If you don't have a non-LDAP account with an identity more secure than passwordless, then you can use the test account "moz.parsys@gmail.com". You can find the password in aws -> parameter store -> /iam/automated-test/github_password. 
Trying to login passwordless in CV admin using that email address will return you the forbidden error, asking to login with github, as that's the most secure Idp.

**Comment by gene1wood** [comment] 2018-08-28 18:06
Ok, I've found out the cause of this. Turns out CI doesn't work with auth0-deploy and so #213 which was merged, was never deployed (cc @hidde for future reference). I'll go about deploying it and will update the ticket when it's deployed at which point this GitHub issue should be solved.

**Comment by gene1wood** [comment] 2018-08-28 21:12
This has been deployed to Auth0-dev. I'm now able to get past this error message.

I do now get an `Unauthorized` error on common voice, but I suspect that this is because I'm not an admin.

Please re-open this if my deploying the code in #213 to auth0-dev did not fix the problem for you.

**Closed by gene1wood** 2018-08-28 21:12 UTC
